// This file was auto-generated by ML.NET Model Builder. 

using System;
using Dr_Heart_Specialist_apiML.Model;

namespace Dr_Heart_Specialist_apiML.ConsoleApp
{
    class Program
    {
        static void Main(string[] args)
        {
            // Create single instance of sample data from first line of dataset for model input
            ModelInput sampleData = new ModelInput()
            {
                Age = 64F,
                Gender = 1F,
                Chestpain = 1F,
                Bloodpressure = 110F,
                Fbs = 0F,
                Maxheartrate = 144F,
                Anigna = 1F,
            };

            // Make a single prediction on the sample data and print results
            var predictionResult = ConsumeModel.Predict(sampleData);

            Console.WriteLine("Using model to make single prediction -- Comparing actual Diagnosis with predicted Diagnosis from sample data...\n\n");
            Console.WriteLine($"Age: {sampleData.Age}");
            Console.WriteLine($"Gender: {sampleData.Gender}");
            Console.WriteLine($"Chestpain: {sampleData.Chestpain}");
            Console.WriteLine($"Bloodpressure: {sampleData.Bloodpressure}");
            Console.WriteLine($"Fbs: {sampleData.Fbs}");
            Console.WriteLine($"Maxheartrate: {sampleData.Maxheartrate}");
            Console.WriteLine($"Anigna: {sampleData.Anigna}");
            Console.WriteLine($"\n\nPredicted Diagnosis value {predictionResult.Prediction} \nPredicted Diagnosis scores: [{String.Join(",", predictionResult.Score)}]\n\n");
            Console.WriteLine("=============== End of process, hit any key to finish ===============");
            Console.ReadKey();
        }
    }
}
