//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dr_Heart_Specialist_api.DataBaseEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONSULTANT_DATA
    {
        public string Consultant_Name { get; set; }
        public string Consultant_Email { get; set; }
        public string Username { get; set; }
    
        public virtual USER_REGISTER_DATA USER_REGISTER_DATA { get; set; }
    }
}
