//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dr_Heart_Specialist_api.DataBaseEntity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Dr_Heart_Specialist_api_db : DbContext
    {
        public Dr_Heart_Specialist_api_db()
            : base("name=Dr_Heart_Specialist_api_db")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ADVANCE_PREDICTION_DATA> ADVANCE_PREDICTION_DATA { get; set; }
        public virtual DbSet<Avg_User_Prediction_Results> Avg_User_Prediction_Results { get; set; }
        public virtual DbSet<CONSULTANT_DATA> CONSULTANT_DATA { get; set; }
        public virtual DbSet<Login_Time> Login_Time { get; set; }
        public virtual DbSet<REGULAR_PREDICTION_DATA> REGULAR_PREDICTION_DATA { get; set; }
        public virtual DbSet<User_Info> User_Info { get; set; }
        public virtual DbSet<USER_LOGIN> USER_LOGIN { get; set; }
        public virtual DbSet<User_Prediction_Results> User_Prediction_Results { get; set; }
        public virtual DbSet<USER_REGISTER_DATA> USER_REGISTER_DATA { get; set; }
    }
}
