//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dr_Heart_Specialist_api.DataBaseEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class USER_REGISTER_DATA
    {
        public string First_Name { get; set; }
        public string Last_Name { get; set; }
        public string Address { get; set; }
        public long Contact_No { get; set; }
        public string Username { get; set; }
    
        public virtual CONSULTANT_DATA CONSULTANT_DATA { get; set; }
        public virtual USER_LOGIN USER_LOGIN { get; set; }
    }
}
