//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dr_Heart_Specialist_api.DataBaseEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class USER_LOGIN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public USER_LOGIN()
        {
            this.Login_Time = new HashSet<Login_Time>();
            this.REGULAR_PREDICTION_DATA = new HashSet<REGULAR_PREDICTION_DATA>();
        }
    
        public string Username { get; set; }
        public string Password { get; set; }
        public string Email { get; set; }
        public string Salt { get; set; }
    
        public virtual ADVANCE_PREDICTION_DATA ADVANCE_PREDICTION_DATA { get; set; }
        public virtual Avg_User_Prediction_Results Avg_User_Prediction_Results { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Login_Time> Login_Time { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<REGULAR_PREDICTION_DATA> REGULAR_PREDICTION_DATA { get; set; }
        public virtual User_Info User_Info { get; set; }
        public virtual User_Prediction_Results User_Prediction_Results { get; set; }
        public virtual USER_REGISTER_DATA USER_REGISTER_DATA { get; set; }
    }
}
